server:
  port: 8060


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/employee/**

        - id: department-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/department/**
